export const GET_PHYSICAL = "GET_PHYSICAL";
export const GET_SOCIAL = 'GET_SOCIAL';
export const GET_PH_MILESTONE = 'GET_PH_MILESTONE';
export const GET_SO_MILESTONE = 'GET_SO_MILESTONE';
export const MILESTONE_STATUS = "MILESTONE_STATUS"

